const PRODUCTS_LOADED = 'PRODUCTS_LOADED'
const PRODUCT_ADDED = 'PRODUCT_ADDED'
const PRODUCT_REMOVED = 'PRODUCT_REMOVED'
const OPEN_CART = 'OPEN_CART'
const CLOSE_CART = 'CLOSE_CART'

export { PRODUCTS_LOADED, PRODUCT_ADDED, PRODUCT_REMOVED, OPEN_CART, CLOSE_CART }
